### ISSUE TITLE
TS Types question

### ISSUE THREAD

**Issue by mrfy** [viniciushvc/vue-testing#1]
Hi Vinicius, very nice example. I have analyzed the code and I've got one question. How is it realized in this example that you have one interface created (`types/todo.ts`) that is available to all places in the application?
If I create another interface file it doesn't work, what could be the reason?

Thanks!

**Comment by vinihvc** [comment]
Sorry @mrfy for the delay in responding, when I started this project I was learning Typescript, now I'm checking the code and I don't understand why that works LOL

**Comment by mrfy** [comment]
@viniciushvc  hahaha :) ok i understand, thanks for answer
